"""Single source of truth for all VoicePaste constants."""

from pynput import keyboard

SAMPLE_RATE: int = 16000
MAX_DURATION: int = 60  # seconds — safety auto-stop
MIN_RECORDING_SECONDS: float = 0.3
MODEL_SIZE: str = "base.en"
DEVICE: str = "cpu"
COMPUTE_TYPE: str = "int8"  # quantized — smaller, faster, same quality
HOTKEY: keyboard.Key = keyboard.Key.alt_r
LOG_TIME_FORMAT: str = "%Y-%m-%d %H:%M:%S.%f"
OVERLAY_BOTTOM_MARGIN: float = 16.0
OVERLAY_CANVAS_PADDING_X: float = 22.0
OVERLAY_CANVAS_PADDING_Y: float = 12.0
OVERLAY_IDLE_WIDTH: float = 58.0
OVERLAY_IDLE_HEIGHT: float = 12.0
OVERLAY_RECORDING_WIDTH: float = 96.0
OVERLAY_RECORDING_HEIGHT: float = 36.0
OVERLAY_PROCESSING_WIDTH: float = 82.0
OVERLAY_PROCESSING_HEIGHT: float = 36.0
OVERLAY_CORNER_RADIUS_MULTIPLIER: float = 0.5
OVERLAY_SHADOW_BLUR: float = 18.0
OVERLAY_SHADOW_ALPHA: float = 0.2
OVERLAY_PILL_ALPHA: float = 1.0
OVERLAY_BORDER_WIDTH: float = 1.5
OVERLAY_BORDER_ALPHA: float = 0.92
OVERLAY_RECORDING_GLOW_ALPHA: float = 0.26
OVERLAY_RECORDING_GLOW_SCALE: float = 1.28
OVERLAY_ANIMATION_FPS: float = 30.0
OVERLAY_TRANSITION_SECONDS: float = 0.18
OVERLAY_RECORDING_PULSE_SECONDS: float = 1.0
OVERLAY_RECORDING_BAR_COUNT: int = 7
OVERLAY_RECORDING_BAR_WIDTH: float = 4.0
OVERLAY_RECORDING_BAR_GAP: float = 3.0
OVERLAY_RECORDING_BAR_MIN_HEIGHT: float = 8.0
OVERLAY_RECORDING_BAR_MAX_HEIGHT: float = 18.0
OVERLAY_PROCESSING_DOT_COUNT: int = 3
OVERLAY_PROCESSING_DOT_SIZE: float = 7.0
OVERLAY_PROCESSING_DOT_GAP: float = 8.0
OVERLAY_PROCESSING_CYCLE_SECONDS: float = 0.85

READABILITY_MODE: str = "off"  # "off" or "openai"
OPENAI_MODEL: str = "gpt-4o-mini"
OPENAI_TIMEOUT_SECONDS: int = 5
OPENAI_MAX_OUTPUT_TOKENS: int = 500
OPENAI_API_KEY_ENV: str = "OPENAI_API_KEY"
MIN_TEXT_LENGTH_FOR_ENHANCEMENT: int = 50
